name: Build R Package

on:
  push:
    branches:
      - fix-size-pkg
  workflow_dispatch:  # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("devtools")'

      - name: Build package
        run: |
          Rscript -e 'devtools::build(path = "artifacts")'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: r-package
          path: artifacts/*.tar.gz
          retention-days: 7
